services:
  - type: web
    name: johera
    env: python
    buildCommand: pip install -r requirements.txt && npm install && npm run build
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.17.0

